;;; squeakyv.el --- Simple SQLite-backed cache -*- lexical-binding: t -*-

;; Author: squeakyv contributors
;; Version: 0.1.0
;; Package-Requires: ((emacs "29.1"))
;; Keywords: cache, sqlite, database
;; URL: https://github.com/squeakyv/squeakyv

;;; Commentary:

;; squeakyv provides a simple SQLite-backed key-value cache for Emacs.
;; Requires Emacs 29.1+ with built-in SQLite support.
;;
;; Basic usage:
;;
;;   (require 'sqlite)
;;   (setq db (sqlite-open "cache.db"))
;;   (squeakyv-init-db db)
;;   (squeakyv-set-value db "key" "value")
;;   (squeakyv-get-current-value db "key")
;;
;; Auto-generated by squeakyv build pipeline. DO NOT EDIT.

;;; Code:

(require 'sqlite)


(defun squeakyv-init-db (db)

  "Initialize database schema in DB.

DB should be a SQLite database handle from `sqlite-open'."

  ;; Auto-generated schema initialization

  (sqlite-execute db "CREATE TABLE IF NOT EXISTS __metadata__ ( key TEXT NOT NULL PRIMARY KEY, value TEXT NOT NULL );")

  (sqlite-execute db "CREATE TABLE IF NOT EXISTS kv ( inserted_at INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)), is_active INTEGER NOT NULL DEFAULT (1) CHECK (is_active IN (0,1)), key TEXT NOT NULL, value BLOB NOT NULL );")

  (sqlite-execute db "INSERT OR IGNORE INTO __metadata__ (key, value) VALUES ('schema_version', '1.0.0');")

  (sqlite-execute db "INSERT OR IGNORE INTO __metadata__ (key, value) VALUES ('schema_tree_ish', 'git-hash-abc123');")

  (sqlite-execute db "INSERT OR IGNORE INTO __metadata__ (key, value) VALUES ('creation_date', strftime('%Y-%m-%dT%H:%M:%f', 'now'));")

  (sqlite-execute db "CREATE UNIQUE INDEX IF NOT EXISTS kv_active_key ON kv(key) WHERE is_active = 1;")

  (sqlite-execute db "CREATE INDEX IF NOT EXISTS kv_key_time ON kv(key, inserted_at);")

  (sqlite-execute db "CREATE TRIGGER IF NOT EXISTS kv_swap_active BEFORE INSERT ON kv FOR EACH ROW BEGIN UPDATE kv SET is_active = 0 WHERE key = NEW.key AND is_active = 1; END;")

  (sqlite-execute db "CREATE VIEW IF NOT EXISTS kv_current AS SELECT key, value, inserted_at FROM kv WHERE is_active = 1;")

  nil)


(defun squeakyv-delete-key (db key)
  "Execute delete_key operation."
  (let ((sql "UPDATE kv\nSET is_active = 0\nWHERE key = ? AND is_active = 1;")
        (params (list key)))
    (sqlite-execute db sql params)
    nil))


(defun squeakyv-get-current-value (db key)
  "Execute get_current_value operation."
  (let ((sql "SELECT value -- , inserted_at\nFROM kv\nWHERE key = ? AND is_active = 1;")
        (params (list key)))
    ;; Return first value from first row, or nil
    (let ((result (sqlite-select db sql params)))
      (if result
          (car (car result))
        nil))))


(defun squeakyv-list-active-keys (db)
  "Execute list_active_keys operation."
  (let ((sql "SELECT key -- , inserted_at\nFROM kv\nWHERE is_active = 1\nORDER BY inserted_at DESC;")
        (params (list)))
    ;; Return list of values (first column from each row)
    (mapcar #'car (sqlite-select db sql params))))


(defun squeakyv-set-value (db key value)
  "Execute set_value operation."
  (let ((sql "INSERT INTO kv (key, value)\nVALUES (?, ?);")
        (params (list key value)))
    (sqlite-execute db sql params)
    nil))


(provide 'squeakyv)
;;; squeakyv.el ends here
