#!/usr/bin/env bash
# Auto-generated SQLite operations for squeakyv (Bash)
# DO NOT EDIT THIS FILE MANUALLY - it is generated by the build pipeline.
# Source: generators/languages/bash.py

set -euo pipefail

SQUEAKYV_DEBUG="${SQUEAKYV_DEBUG:-0}"


# Embedded database schema
SQUEAKYV_SCHEMA_SQL=$(cat <<'SQUEAKYV_SCHEMA_EOF'
/*
 * Table: __metadata__
 * Description: Database internal metadata table
 */
CREATE TABLE IF NOT EXISTS __metadata__ (
  -- Metadata key (e.g., 'schema_version', 'creation_date')
  key TEXT NOT NULL PRIMARY KEY,
  -- Associated value for the metadata key
  value TEXT NOT NULL
);

/*
 * Table: kv
 * Description: Single key-value table storing arbitrary values
 */
CREATE TABLE IF NOT EXISTS kv (
  -- UNIX insertion time (milliseconds)
  inserted_at INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  -- Logical active flag (0 or 1)
  is_active INTEGER NOT NULL DEFAULT (1) CHECK (is_active IN (0,1)),
  -- Logical key identifier
  key TEXT NOT NULL,
  -- Arbitrary payload stored as BLOB for maximum compatibility
  value BLOB NOT NULL
);


/*
 * Initialization Data: Schema Version and Creation Date (Idempotent)
 * These records are only inserted if they do not already exist.
 */
INSERT OR IGNORE INTO __metadata__ (key, value) VALUES ('schema_version', '1.0.0');
INSERT OR IGNORE INTO __metadata__ (key, value) VALUES ('schema_tree_ish', 'git-hash-abc123');
INSERT OR IGNORE INTO __metadata__ (key, value) VALUES ('creation_date', strftime('%Y-%m-%dT%H:%M:%f', 'now'));

-- Only one active row per key
CREATE UNIQUE INDEX IF NOT EXISTS kv_active_key ON kv(key) WHERE is_active = 1;

-- Time-travel and scans
CREATE INDEX IF NOT EXISTS kv_key_time ON kv(key, inserted_at);

-- Swap-out on overwrite: retire old active row just before insert
CREATE TRIGGER IF NOT EXISTS kv_swap_active
BEFORE INSERT ON kv
FOR EACH ROW
BEGIN
  UPDATE kv SET is_active = 0
  WHERE key = NEW.key AND is_active = 1;
END;

-- Convenience view
CREATE VIEW IF NOT EXISTS kv_current AS
  SELECT key, value, inserted_at
  FROM kv
  WHERE is_active = 1;


SQUEAKYV_SCHEMA_EOF
)


# Internal: Execute parameterized SQL query
# Args: db_path, sql, param_name1, param_value1, param_name2, param_value2, ...
_squeakyv_execute() {
    local db_path="$1"
    local sql="$2"
    shift 2

    local sqlite_input="$sql"

    # Build parameter assignments
    while [[ $# -gt 0 ]]; do
        local param_name="$1"
        local param_value="$2"
        shift 2

        # SQLite CLI parameter binding (before the SQL statement)
        sqlite_input=".param set :${param_name} '${param_value}'
${sqlite_input}"
    done

    if [[ "$SQUEAKYV_DEBUG" -gt 0 ]]; then
        echo "[DEBUG] SQL: $sql" >&2
        echo "[DEBUG] Input: $sqlite_input" >&2
    fi

    echo "$sqlite_input" | sqlite3 "$db_path"
}

# Internal: Execute SQL query and return single value
_squeakyv_query_one() {
    local db_path="$1"
    local sql="$2"
    shift 2

    local sqlite_input="$sql"

    while [[ $# -gt 0 ]]; do
        local param_name="$1"
        local param_value="$2"
        shift 2
        sqlite_input=".param set :${param_name} '${param_value}'
${sqlite_input}"
    done

    if [[ "$SQUEAKYV_DEBUG" -gt 0 ]]; then
        echo "[DEBUG] SQL: $sql" >&2
    fi

    echo "$sqlite_input" | sqlite3 "$db_path"
}

# Internal: Execute SQL query and return multiple rows
_squeakyv_query_all() {
    local db_path="$1"
    local sql="$2"
    shift 2

    local sqlite_input="$sql"

    while [[ $# -gt 0 ]]; do
        local param_name="$1"
        local param_value="$2"
        shift 2
        sqlite_input=".param set :${param_name} '${param_value}'
${sqlite_input}"
    done

    if [[ "$SQUEAKYV_DEBUG" -gt 0 ]]; then
        echo "[DEBUG] SQL: $sql" >&2
    fi

    echo "$sqlite_input" | sqlite3 "$db_path"
}

# Initialize database schema
squeakyv_init_db() {
    local db_path="$1"

    if [[ -z "${SQUEAKYV_SCHEMA_SQL:-}" ]]; then
        echo "Error: SQUEAKYV_SCHEMA_SQL not defined" >&2
        return 1
    fi

    echo "$SQUEAKYV_SCHEMA_SQL" | sqlite3 "$db_path"
}


# Execute delete_key operation
squeakyv_delete_key() {
    local db_path="$1"
    local key="$2"

    local sql=$(cat <<'SQUEAKYV_SQL_EOF'
UPDATE kv
SET is_active = 0
WHERE key = :key AND is_active = 1;
SQUEAKYV_SQL_EOF
)

    _squeakyv_execute "$db_path" "$sql" "key" "$key"
}


# Execute get_current_value operation
squeakyv_get_current_value() {
    local db_path="$1"
    local key="$2"

    local sql=$(cat <<'SQUEAKYV_SQL_EOF'
SELECT value -- , inserted_at
FROM kv
WHERE key = :key AND is_active = 1;
SQUEAKYV_SQL_EOF
)

    _squeakyv_query_one "$db_path" "$sql" "key" "$key"
}


# Execute list_active_keys operation
squeakyv_list_active_keys() {
    local db_path="$1"

    local sql=$(cat <<'SQUEAKYV_SQL_EOF'
SELECT key -- , inserted_at
FROM kv
WHERE is_active = 1
ORDER BY inserted_at DESC;
SQUEAKYV_SQL_EOF
)

    _squeakyv_query_all "$db_path" "$sql"
}


# Execute set_value operation
squeakyv_set_value() {
    local db_path="$1"
    local key="$2"
    local value="$3"

    local sql=$(cat <<'SQUEAKYV_SQL_EOF'
INSERT INTO kv (key, value)
VALUES (:key, :value);
SQUEAKYV_SQL_EOF
)

    _squeakyv_execute "$db_path" "$sql" "key" "$key" "value" "$value"
}
